import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Template } from "@pdfme/common";
import { generate } from "@pdfme/generator";
import { line, text } from "@pdfme/schemas";
import type { CV } from "@/lib/schemas";

// ─── Template tokens ──────────────────────────────────────────
const INK = "#17171a";
const MUTED = "#5d5d5a";
const FAINT = "#a8a69c";
const ACCENT = "#067a3e";
const RULE = "#d6d3c8";

const cvTemplate: Template = {
	basePdf: {
		width: 210,
		height: 297,
		padding: [18, 22, 18, 22],
		staticSchema: [
			{
				name: "footerRule",
				type: "line",
				position: { x: 22, y: 284 },
				width: 166,
				height: 0.2,
				color: RULE,
			},
			{
				name: "footerLeft",
				type: "text",
				position: { x: 22, y: 287 },
				width: 100,
				height: 6,
				fontSize: 8,
				fontColor: FAINT,
				content: "cv · generated by agents-101",
				readOnly: true,
			},
			{
				name: "footerRight",
				type: "text",
				position: { x: 122, y: 287 },
				width: 66,
				height: 6,
				fontSize: 8,
				fontColor: FAINT,
				alignment: "right",
				content: "Page {currentPage} / {totalPages}",
				readOnly: true,
			},
		],
	},
	schemas: [
		[
			// ── Header ────────────────────────────────
			{
				name: "name",
				type: "text",
				position: { x: 22, y: 22 },
				width: 166,
				height: 14,
				fontSize: 28,
				fontColor: INK,
				alignment: "left",
				verticalAlignment: "middle",
			},
			{
				name: "headline",
				type: "text",
				position: { x: 22, y: 38 },
				width: 166,
				height: 10,
				fontSize: 12,
				fontColor: MUTED,
				alignment: "left",
				verticalAlignment: "middle",
			},
			{
				name: "headerRule",
				type: "line",
				position: { x: 22, y: 52 },
				width: 166,
				height: 0.3,
				color: RULE,
			},

			// ── Skills ────────────────────────────────
			{
				name: "skillsLabel",
				type: "text",
				position: { x: 22, y: 58 },
				width: 166,
				height: 6,
				fontSize: 9,
				fontColor: ACCENT,
				characterSpacing: 2,
				content: "SKILLS",
				readOnly: true,
			},
			{
				name: "skills",
				type: "text",
				position: { x: 22, y: 64 },
				width: 166,
				height: 16,
				fontSize: 10,
				fontColor: INK,
				lineHeight: 1.5,
			},

			// ── Experience ────────────────────────────
			{
				name: "expLabel",
				type: "text",
				position: { x: 22, y: 86 },
				width: 166,
				height: 6,
				fontSize: 9,
				fontColor: ACCENT,
				characterSpacing: 2,
				content: "EXPERIENCE",
				readOnly: true,
			},
			{
				name: "jobs",
				type: "text",
				position: { x: 22, y: 94 },
				width: 166,
				height: 180,
				fontSize: 10,
				fontColor: INK,
				lineHeight: 1.55,
				dynamicFontSize: { min: 8, max: 10, fit: "vertical" },
			},
		],
	],
};

export type RenderedCV = { url: string; bytes: number };

export async function renderCVtoPdf(cv: CV): Promise<RenderedCV> {
	const jobsRendered = cv.jobs
		.map((j) => {
			const head = [j.role, j.company && `@ ${j.company}`, j.years && `· ${j.years}`]
				.filter(Boolean)
				.join(" ");
			const bullets = (j.highlights ?? [])
				.map((h) => `  •  ${h}`)
				.join("\n");
			return bullets ? `${head}\n${bullets}` : head;
		})
		.join("\n\n");

	const pdf = await generate({
		template: cvTemplate,
		inputs: [
			{
				name: cv.name,
				headline: cv.headline ?? "",
				skills: cv.skills.join("  ·  "),
				jobs: jobsRendered,
			},
		],
		plugins: { text, line },
	});

	const id = crypto.randomUUID().slice(0, 8);
	const dir = join(process.cwd(), "public", "cvs");
	await mkdir(dir, { recursive: true });
	await writeFile(join(dir, `${id}.pdf`), pdf);

	return { url: `/cvs/${id}.pdf`, bytes: pdf.length };
}
